name: Keep Render API Alive

on:
  schedule:
    - cron: '*/14 * * * *'  # every 14 minutes
  workflow_dispatch:        # Allows manual triggering from the GitHub UI

jobs:
  run_task:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Run a script
        run: curl https://bookmark-manager-api-latest-hkyo.onrender.com/api/health